Added cfn template and lambda code for alert
qrstuff/rds-slack-alerts pull request #1
Opened 2024-04-08 02:05 UTC by skzmego

2024-04-08 04:57 UTC, vaibhavqrcg requested changes

2024-04-08 04:57 UTC, vaibhavqrcg commented on alert-notification/lambda_function.py
> +                        "value": "Cloudwatch Alarm-AWS",
See if after removeing the action_id & value, the triangle issue is gone. I'm hopeful.

2024-04-09 09:09 UTC, skzmego commented on alert-notification/lambda_function.py
> +                        "value": "Cloudwatch Alarm-AWS",
No luck 
![image](https://github.com/qrstuff/rds-slack-alerts/assets/140999566/07c4a8a3-f131-4bb7-8c03-8cf06446c8e9)

2024-04-15 04:42 UTC, vaibhavqrcg requested changes

2024-04-15 04:42 UTC, vaibhavqrcg commented on alert-notification/lambda_function.py
> +    print(response)
Can we also remove debug statements?

2024-04-15 04:42 UTC, vaibhavqrcg commented on alert-notification/lambda_function.py
> +    print(response)
Remove this too.

2024-04-15 04:42 UTC, vaibhavqrcg commented on alert-notification/lambda_function.py
> +    print(response)
@skzmego we need to remove this?

2024-04-15 04:42 UTC, vaibhavqrcg commented on alert-notification/lambda_function.py
> +    print(response)
This as well.

2024-04-15 06:39 UTC, vaibhavqrcg commented
Should include a README file.

2024-04-15 06:41 UTC, vaibhavqrcg approved these changes
Good to merge with a README

2024-04-16 06:21 UTC, vaibhavqrcg commented on alert-notification/lambda_function.py
> +    print(response)
Yes, no debug statements.

2024-04-16 08:41 UTC, merged